"""
01_hopf_constants_table_en.py

Computes the Hopf constants used in the sensitivity table.

For each logistic function f, the script computes:
    a_H, 1/a_H, omega_0, G_4, ell_1(0).

The formulas correspond to the humped-memory predator-prey model
in the reparametrized system:
    n' = n f(n) - K alpha n p,
    p' = -gamma p + K beta p q,
    q' = a(r-q),
    r' = a(n-r).

Output:
    data/hopf_constants_table_en.csv
    data/hopf_constants_table_en.tex
"""

from pathlib import Path
import csv
import numpy as np


# ---------------------------------------------------------------------
# Output paths are relative to the location of this script.
# ---------------------------------------------------------------------
try:
    BASE_DIR = Path(__file__).resolve().parent
except NameError:
    BASE_DIR = Path.cwd()

DATA_DIR = BASE_DIR.parent / "data" if BASE_DIR.name == "scripts" else BASE_DIR / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------
# Fixed parameters for the comparison table
# ---------------------------------------------------------------------
K = 2.0
alpha = 1.0
beta = 1.0
gamma = 1.0
b = gamma / (K * beta)


def positive_root_of_phi(F, G):
    """Return the positive real root of the cubic Phi(a)."""
    coeffs = [
        1.0,
        2.0 * K * beta * F / G - 2.0 * b * G,
        b * (b * G**2 - 2.0 * K * beta * F),
        0.5 * K * beta * b**2 * F * G,
    ]
    roots = np.roots(coeffs)
    real_positive = [z.real for z in roots if abs(z.imag) < 1e-8 and z.real > 0]
    if len(real_positive) != 1:
        raise RuntimeError(f"Expected one positive real root, got {roots}.")
    return real_positive[0]


def hopf_frequency(a_H, G):
    """Critical Hopf frequency omega_0."""
    return np.sqrt(-(a_H**2) * b * G / (2.0 * a_H - b * G))


def G4_and_l1(F, G, H, S, a_H, omega):
    """Compute G_4 and ell_1(0) using the compact algebraic formula."""
    kappa = K * alpha
    rho = K * beta
    a = a_H
    w = omega

    A = np.array(
        [
            [b * G, -kappa * b, 0.0, 0.0],
            [0.0, 0.0, rho * F / kappa, 0.0],
            [0.0, 0.0, -a, a],
            [a, 0.0, 0.0, -a],
        ],
        dtype=complex,
    )

    q1 = 1.0 + 0.0j
    q2 = (b * G - 1j * w) / (kappa * b)
    q3 = 1j * w * (b * G - 1j * w) / (rho * F * b)
    q4 = (a + 1j * w) * 1j * w * (b * G - 1j * w) / (a * rho * F * b)
    q = np.array([q1, q2, q3, q4], dtype=complex)

    def B(x, y):
        z = np.zeros(4, dtype=complex)
        z[0] = 2.0 * (G + b * H / 2.0) * x[0] * y[0] - kappa * (x[0] * y[1] + x[1] * y[0])
        z[1] = rho * (x[1] * y[2] + x[2] * y[1])
        return z

    h = np.linalg.solve(2j * w * np.eye(4) - A, B(q, q))
    h1, h2, h3, _ = h

    m = (a * b * G + 3j * b * G * w - 2j * a * w + 4.0 * w**2) / (w * (w - 1j * a))

    d1 = H + b * S + (G + b * H - 1j * w / b) * h1 - kappa * h2
    d2 = (2.0 * rho * H / kappa) * q3 + rho * (np.conj(q2) * h3 + np.conj(q3) * h2)

    G4 = np.real((d1 + 1j * kappa * b * d2 / w) / m)
    ell1 = G4 / (2.0 * w)
    return G4, ell1


def compute_row(label, F, G, H, S):
    a_H = positive_root_of_phi(F, G)
    omega = hopf_frequency(a_H, G)
    G4, ell1 = G4_and_l1(F, G, H, S, a_H, omega)
    return {
        "function": label,
        "a_H": a_H,
        "1/a_H": 1.0 / a_H,
        "omega_0": omega,
        "G_4": G4,
        "ell_1(0)": ell1,
        "criticality": "supercritical" if ell1 < 0 else "subcritical",
    }


# ---------------------------------------------------------------------
# Logistic functions evaluated at b = 1/2
# ---------------------------------------------------------------------
rows = []

# f(n) = 1 - n
rows.append(compute_row("1-n", 1.0 - b, -1.0, 0.0, 0.0))

# f(n) = 1 - n^2
rows.append(compute_row("1-n^2", 1.0 - b**2, -2.0 * b, -2.0, 0.0))

# f(n) = 1 - n^3
rows.append(compute_row("1-n^3", 1.0 - b**3, -3.0 * b**2, -6.0 * b, -6.0))

# f(n) = (1-n)^2
rows.append(compute_row("(1-n)^2", (1.0 - b) ** 2, -2.0 * (1.0 - b), 2.0, 0.0))


# ---------------------------------------------------------------------
# Save CSV
# ---------------------------------------------------------------------
csv_path = DATA_DIR / "hopf_constants_table_en.csv"
with csv_path.open("w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    writer.writeheader()
    writer.writerows(rows)


# ---------------------------------------------------------------------
# Save a small LaTeX table fragment
# ---------------------------------------------------------------------
tex_path = DATA_DIR / "hopf_constants_table_en.tex"
with tex_path.open("w", encoding="utf-8") as f:
    f.write("% Generated by 01_hopf_constants_table_en.py\n")
    f.write("\\begin{tabular}{lccccc}\n")
    f.write("\\toprule\n")
    f.write("Function & $a_{\\mathrm H}$ & $1/a_{\\mathrm H}$ & $\\omega_0$ & $G_4$ & $\\ell_1(0)$ \\\\\n")
    f.write("\\midrule\n")
    for row in rows:
        f.write(
            f"${row['function']}$ & "
            f"{row['a_H']:.6f} & {row['1/a_H']:.6f} & {row['omega_0']:.6f} & "
            f"{row['G_4']:.6f} & {row['ell_1(0)']:.6f} \\\\\n"
        )
    f.write("\\bottomrule\n")
    f.write("\\end{tabular}\n")


# ---------------------------------------------------------------------
# Print results
# ---------------------------------------------------------------------
print("Hopf constants table")
for row in rows:
    print(
        f"{row['function']:10s}  "
        f"a_H={row['a_H']:.12f}  "
        f"1/a_H={row['1/a_H']:.12f}  "
        f"omega_0={row['omega_0']:.12f}  "
        f"G_4={row['G_4']:.12f}  "
        f"ell_1={row['ell_1(0)']:.12f}  "
        f"{row['criticality']}"
    )

print("Generated files:")
print(f"  {csv_path}")
print(f"  {tex_path}")
